// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxqzzmclmO3xmz3AhYiLEJQ4YiiL5Gsg',
    appId: '1:117850494101:web:c69b2181c4e1c64ca7f79c',
    messagingSenderId: '117850494101',
    projectId: 'todoapp-419b3',
    authDomain: 'todoapp-419b3.firebaseapp.com',
    storageBucket: 'todoapp-419b3.appspot.com',
    measurementId: 'G-WMLTDP537Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoO4DOcVvk5JFdzZmR62yQvtSSA_rDv2s',
    appId: '1:117850494101:android:87b7e64ff49c245ea7f79c',
    messagingSenderId: '117850494101',
    projectId: 'todoapp-419b3',
    storageBucket: 'todoapp-419b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdVCfJWlm7T-fU_fiVK9bOkTROqjZGCag',
    appId: '1:117850494101:ios:f37bcab76b17b285a7f79c',
    messagingSenderId: '117850494101',
    projectId: 'todoapp-419b3',
    storageBucket: 'todoapp-419b3.appspot.com',
    iosBundleId: 'com.example.todoappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdVCfJWlm7T-fU_fiVK9bOkTROqjZGCag',
    appId: '1:117850494101:ios:f37bcab76b17b285a7f79c',
    messagingSenderId: '117850494101',
    projectId: 'todoapp-419b3',
    storageBucket: 'todoapp-419b3.appspot.com',
    iosBundleId: 'com.example.todoappfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnxqzzmclmO3xmz3AhYiLEJQ4YiiL5Gsg',
    appId: '1:117850494101:web:b896b7761454d313a7f79c',
    messagingSenderId: '117850494101',
    projectId: 'todoapp-419b3',
    authDomain: 'todoapp-419b3.firebaseapp.com',
    storageBucket: 'todoapp-419b3.appspot.com',
    measurementId: 'G-8PN3XZSLCE',
  );
}
